export const arrayNames = [
  { name: "최고의 전망", image: "bestview" },
  { name: "한적한 시골", image: "countryside" },
  { name: "멋진 수영장", image: "swimmingpool" },
  { name: "캐슬", image: "castle" },
  { name: "저택", image: "mansion" },
  { name: "방", image: "room" },
  { name: "한옥", image: "hanock" },
  { name: "캠핑장", image: "camping" },
  { name: "초소형 주택", image: "smallhouse" },
  { name: "해변 바로 앞", image: "beach" },
  { name: "국립공원", image: "nationalpark" },
  { name: "속세를 벗어난 숙소", image: "quietaccommodation" },
  { name: "기상천외한 숙소", image: "unimaginable" },
  { name: "인기 급상승", image: "populer" },
  { name: "풍차", image: "windmill" },
  { name: "통나무집", image: "woodhouse" },
  { name: "농장", image: "farm" },
  { name: "디자인", image: "design" },
  { name: "스키", image: "ski" },
  { name: "무장애", image: "mujang" },
  { name: "트리하우스", image: "treehouse" },
  { name: "서핑", image: "surfing" },
  { name: "료칸", image: "ryokan" },
  { name: "열대 지역", image: "tropicalplace" },
  { name: "호수 근처", image: "lake" },
  { name: "상징적 도시", image: "landmark" },
  { name: "키즈", image: "kids" },
  { name: "유서 깊은 주택", image: "historichouse" },
  { name: "사막", image: "desert" },
  { name: "컨테이너하우스", image: "containerhouse" },
  { name: "카사 파르티쿨라르", image: "kasapartikular" },
  { name: "타워", image: "tower" },
  { name: "호숫가", image: "lakeside" },
  { name: "섬", image: "island" },
  { name: "스키 타고 출입", image: "skiandenter" },
  { name: "A자형 주택", image: "ashapedhouse" },
  { name: "민수", image: "minsu" },
  { name: "와인 농장", image: "winefarm" },
  { name: "신규", image: "new" },
  { name: "북극", image: "northpole" },
  { name: "담무소", image: "dammuso" },
  { name: "세상의 꼭대기", image: "topoftheworld" },
  { name: "복토 주택", image: "bocktohouse" },
  { name: "헛간", image: "barn" },
  { name: "동굴", image: "cave" },
  { name: "B&B", image: "bnb" },
  { name: "캠핑카", image: "campingcar" },
  { name: "골프장", image: "golfcourse" },
  { name: "Luxe", image: "luxe" },
  { name: "키클라데스 주택", image: "kikilradeshouse" },
  { name: "돔하우스", image: "domhouse" },
  { name: "유르트", image: "yurthouse" },
  { name: "마차", image: "carriage" },
  { name: "보트", image: "boat" },
  { name: "창작 공간", image: "creativespace" },
  { name: "그랜드 피아노", image: "grandpiano" },
  { name: "하우스 보트", image: "houseboat" },
  { name: "리아드", image: "riad" },
  { name: "트룰로", image: "troolo" },
  { name: "해변 근처", image: "beachside" },
];
